/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/+mentors/assigned-students/assigned-students.component';
import * as i1 from '../../../../../src/app/app_shared/services/session.service';
import * as i2 from '../../../../../src/app/app_shared/services/sql-resource';
import * as i3 from './assigned-students.component.ngfactory';
export function AssignedStudentsComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AssignedStudentsComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.SessionService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.SqlResource}}}],lifecycleHooks:[0]},isComponent:true,
      selector:'assigned-students',exportAs:(null as any),inputs:{},outputs:{onSelectedStudentName:'onSelectedStudentName',
          onSelectedStudentId:'onSelectedStudentId'},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i3.View_AssignedStudentsComponent_0,
      rendererType:i3.RenderType_AssignedStudentsComponent,componentFactory:i3.AssignedStudentsComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rbWVudG9ycy9hc3NpZ25lZC1zdHVkZW50cy9hc3NpZ25lZC1zdHVkZW50cy5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ja2FwaWxsYS9EZXYvSm92ZW5lc0EtY2xpZW50LkNMSS9zcmMvYXBwLyttZW50b3JzL2Fzc2lnbmVkLXN0dWRlbnRzL2Fzc2lnbmVkLXN0dWRlbnRzLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
