/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/+reports/reports.component';
import * as i1 from '../../../../src/app/app_shared/services/auth.service';
import * as i2 from './reports.component.ngfactory';
export function ReportsComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ReportsComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Auth}}}],
      lifecycleHooks:([] as any[])},isComponent:true,selector:'ja-reports',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i2.View_ReportsComponent_0,
      rendererType:i2.RenderType_ReportsComponent,componentFactory:i2.ReportsComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rcmVwb3J0cy9yZXBvcnRzLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2NrYXBpbGxhL0Rldi9Kb3ZlbmVzQS1jbGllbnQuQ0xJL3NyYy9hcHAvK3JlcG9ydHMvcmVwb3J0cy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
