/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/+home/home.module';
import * as i1 from '../../../../src/app/+home/home.component';
import * as i2 from './home.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/core';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/router';
import * as i7 from '../../../../src/app/app_shared/app_shared.module';
import * as i8 from './home.component.ngsummary';
import * as i9 from '../../../node_modules/@angular/common/common.ngsummary';
import * as i10 from '../../../node_modules/@angular/router/router.ngsummary';
import * as i11 from '../../../node_modules/@angular/forms/forms.ngsummary';
import * as i12 from '../app_shared/app_shared.module.ngsummary';
export function HomeModuleNgSummary():any[] {
  return [{summaryKind:2,type:{reference:i0.HomeModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
      entryComponents:[{componentType:i1.HomeComponent,componentFactory:i2.HomeComponentNgFactory}],
      providers:[{provider:{token:{identifier:{reference:i3.NgLocalization}},useClass:{reference:i3.NgLocaleLocalization,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i4.LOCALE_ID}}}],lifecycleHooks:([] as any[])},
          useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
          deps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i4.LOCALE_ID}}}],multi:false},module:{reference:i3.CommonModule,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i5.FormBuilder,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},useClass:{reference:i5.FormBuilder,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},useValue:(undefined as any),
          useFactory:(null as any),useExisting:(undefined as any),deps:([] as any[]),
          multi:false},module:{reference:i5.ReactiveFormsModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i5.ɵi,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},useClass:{reference:i5.ɵi,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},useValue:(undefined as any),
          useFactory:(null as any),useExisting:(undefined as any),deps:([] as any[]),
          multi:false},module:{reference:i5.ReactiveFormsModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i5.ɵi,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},useClass:{reference:i5.ɵi,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},useValue:(undefined as any),
          useFactory:(null as any),useExisting:(undefined as any),deps:([] as any[]),
          multi:false},module:{reference:i5.FormsModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}},
          {provider:{token:{identifier:{reference:i6.ROUTES}},useClass:(null as any),
              useValue:[{path:'',component:i1.HomeComponent}],useFactory:(null as any),
              useExisting:(undefined as any),deps:(undefined as any),multi:true},module:{reference:i0.HomeModule,
              diDeps:([] as any[]),lifecycleHooks:([] as any[])}}],modules:[{reference:i3.CommonModule,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},{reference:i6.RouterModule,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:true,
              token:{identifier:{reference:i6.ɵa}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:true,token:{identifier:{reference:i6.Router}}}],
          lifecycleHooks:([] as any[])},{reference:i5.ɵbc,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
          {reference:i5.ReactiveFormsModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
          {reference:i5.FormsModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
          {reference:i7.AppSharedModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
          {reference:i0.HomeModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}],
      exportedDirectives:([] as any[]),exportedPipes:([] as any[])},i8.HomeComponentNgSummary,
      i9.CommonModuleNgSummary,i10.RouterModuleNgSummary,i11.ɵbcNgSummary,i11.ReactiveFormsModuleNgSummary,
      i11.FormsModuleNgSummary,i12.AppSharedModuleNgSummary];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8raG9tZS9ob21lLm1vZHVsZS5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2NrYXBpbGxhL0Rldi9Kb3ZlbmVzQS1jbGllbnQuQ0xJL3NyYy9hcHAvK2hvbWUvaG9tZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
