/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/+reports/reports-student-letters/reports-student-letters.component';
import * as i1 from '../../../../../src/app/+reports/shared/services/sql-reports';
import * as i2 from '@angular/router';
import * as i3 from '../../../../../src/app/app_shared/services/session.service';
import * as i4 from './reports-student-letters.component.ngfactory';
export function ReportsStudentLettersComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ReportsStudentLettersComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.SqlReports}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.Router}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.SessionService}}}],
      lifecycleHooks:[0]},isComponent:true,selector:'ng-component',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i4.View_ReportsStudentLettersComponent_0,
      rendererType:i4.RenderType_ReportsStudentLettersComponent,componentFactory:i4.ReportsStudentLettersComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rcmVwb3J0cy9yZXBvcnRzLXN0dWRlbnQtbGV0dGVycy9yZXBvcnRzLXN0dWRlbnQtbGV0dGVycy5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ja2FwaWxsYS9EZXYvSm92ZW5lc0EtY2xpZW50LkNMSS9zcmMvYXBwLytyZXBvcnRzL3JlcG9ydHMtc3R1ZGVudC1sZXR0ZXJzL3JlcG9ydHMtc3R1ZGVudC1sZXR0ZXJzLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
