/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['[_nghost-%COMP%] {\n  display: block;\n  padding: 0 16px;\n}\n\nlabel[_ngcontent-%COMP%] {\n  padding-top: 10px;\n}\n\nradio.ng-touched.ng-invalid[_ngcontent-%COMP%], textarea.ng-touched.ng-invalid[_ngcontent-%COMP%], input.ng-touched.ng-invalid[_ngcontent-%COMP%], select.ng-touched.ng-invalid[_ngcontent-%COMP%] {\n  border: 1px solid #a94442; \n  border-left: 5px solid #a94442; \n }\n\n\nradio.ng-valid[_ngcontent-%COMP%], textarea.ng-valid[_ngcontent-%COMP%], input.ng-valid[_ngcontent-%COMP%], select.ng-valid[_ngcontent-%COMP%] {\n  border-left: 5px solid #42A948; \n}\n\nradio.ng-invalid[_ngcontent-%COMP%], textarea.ng-invalid[_ngcontent-%COMP%], input.ng-invalid[_ngcontent-%COMP%], select.ng-invalid[_ngcontent-%COMP%] {\n  border-left: 5px solid #a94442; \n}\n\n.red[_ngcontent-%COMP%] {\n  color: #a94442;\n  font-weight: bold;\n}'];
//# sourceMappingURL=sponsor-letters-add.component.css.shim.ngstyle.js.map