/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/+students/sponsor-letters-add/sponsor-letters-add.component';
import * as i1 from '@angular/router';
import * as i2 from '../../../../../src/app/app_shared/services/sql-resource';
import * as i3 from '@angular/forms';
import * as i4 from './sponsor-letters-add.component.ngfactory';
export function SponsorLettersAddComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.SponsorLettersAddComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ActivatedRoute}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i1.Router}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.SqlResource}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i3.FormBuilder}}}],lifecycleHooks:[0]},isComponent:true,
      selector:'ng-component',exportAs:(null as any),inputs:{},outputs:{},hostListeners:{},
      hostProperties:{},hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),
      queries:([] as any[]),viewQueries:([] as any[]),entryComponents:([] as any[]),
      changeDetection:1,template:{animations:([] as any[]),ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i4.View_SponsorLettersAddComponent_0,
      rendererType:i4.RenderType_SponsorLettersAddComponent,componentFactory:i4.SponsorLettersAddComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rc3R1ZGVudHMvc3BvbnNvci1sZXR0ZXJzLWFkZC9zcG9uc29yLWxldHRlcnMtYWRkLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2NrYXBpbGxhL0Rldi9Kb3ZlbmVzQS1jbGllbnQuQ0xJL3NyYy9hcHAvK3N0dWRlbnRzL3Nwb25zb3ItbGV0dGVycy1hZGQvc3BvbnNvci1sZXR0ZXJzLWFkZC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
