/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/app_shared/pipes/alpha-language-pipe';
export function AlphaLanguagePipeNgSummary():any[] {
  return [{summaryKind:0,type:{reference:i0.AlphaLanguagePipe,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},name:'alphaLanguage',pure:true}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC9hcHBfc2hhcmVkL3BpcGVzL2FscGhhLWxhbmd1YWdlLXBpcGUubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ja2FwaWxsYS9EZXYvSm92ZW5lc0EtY2xpZW50LkNMSS9zcmMvYXBwL2FwcF9zaGFyZWQvcGlwZXMvYWxwaGEtbGFuZ3VhZ2UtcGlwZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7OyJ9
