/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app_shared/headerbar/headerbar.component.ngfactory';
import * as i2 from '../../../src/app/app_shared/headerbar/headerbar.component';
import * as i3 from '../../../src/app/app_shared/services/auth.service';
import * as i4 from '../../../src/app/app_shared/services/session.service';
import * as i5 from '@angular/router';
import * as i6 from '../../../src/app/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ja-headerbar',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_HeaderbarComponent_0,
      i1.RenderType_HeaderbarComponent)),i0.ɵdid(49152,(null as any),0,i2.HeaderbarComponent,
      [i3.Auth,i4.SessionService],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
      ['\n\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(16777216,(null as any),(null as any),
      1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),i0.ɵdid(212992,(null as any),0,i5.RouterOutlet,[i5.ChildrenOutletContexts,
      i0.ViewContainerRef,i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
      (null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),
      i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,6,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-ja',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i6.AppComponent,[i3.Auth,i4.SessionService,i5.Router],
          (null as any),(null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i6.AppComponent> = i0.ɵccf('app-ja',
    i6.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9ja2FwaWxsYS9EZXYvSm92ZW5lc0EtY2xpZW50LkNMSS9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxqYS1oZWFkZXJiYXI+PC9qYS1oZWFkZXJiYXI+XG5cbjxkaXY+XG48cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG48L2Rpdj5cbiIsIjxhcHAtamE+PC9hcHAtamE+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO3NDQUFBLFVBQUE7TUFBQSx5REFBNkI7TUFBQSxXQUU3QjtNQUFBLHdFQUFLO2FBQUEsd0JBQ0w7TUFBQTtNQUFBLHVCQUFBO3NEQUFBO01BQUEsNkJBQStCLHVDQUN6QjthQUFBO0lBRE47Ozs7b0JDSEE7TUFBQTthQUFBO1VBQUE7OzsifQ==
