/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../src/app/app.routing-guards';
import * as i1 from '../../../src/app/app_shared/services/auth.service';
import * as i2 from '@angular/router';
import * as i3 from '../../../src/app/app_shared/services/session.service';
export function CanActivateViaAdminAuthGuardNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.CanActivateViaAdminAuthGuard,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Auth}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.Router}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.SessionService}}}],
      lifecycleHooks:([] as any[])}}];
}
export function CanActivateViaMentorAuthGuardNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.CanActivateViaMentorAuthGuard,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Auth}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.Router}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.SessionService}}}],
      lifecycleHooks:([] as any[])}}];
}
export function CanActivateViaStudentAuthGuardNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.CanActivateViaStudentAuthGuard,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Auth}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.Router}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.SessionService}}}],
      lifecycleHooks:([] as any[])}}];
}
export function ConfirmDeactivateGuardNgSummary():any[] {
  return [{summaryKind:3,type:{reference:i0.ConfirmDeactivateGuard,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC9hcHAucm91dGluZy1ndWFyZHMubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ja2FwaWxsYS9EZXYvSm92ZW5lc0EtY2xpZW50LkNMSS9zcmMvYXBwL2FwcC5yb3V0aW5nLWd1YXJkcy50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
