/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/+students/students-sponsor-letters/students-sponsor-letters.component';
import * as i1 from '@angular/router';
import * as i2 from '../../../../../src/app/app_shared/services/sql-resource';
import * as i3 from '../../../../../src/app/app_shared/services/session.service';
import * as i4 from './students-sponsor-letters.component.ngfactory';
export function StudentsSponsorLettersComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.StudentsSponsorLettersComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ActivatedRoute}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i1.Router}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.SqlResource}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i3.SessionService}}}],lifecycleHooks:[0]},isComponent:true,
      selector:'ng-component',exportAs:(null as any),inputs:{},outputs:{},hostListeners:{},
      hostProperties:{},hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),
      queries:([] as any[]),viewQueries:([] as any[]),entryComponents:([] as any[]),
      changeDetection:1,template:{animations:([] as any[]),ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i4.View_StudentsSponsorLettersComponent_0,
      rendererType:i4.RenderType_StudentsSponsorLettersComponent,componentFactory:i4.StudentsSponsorLettersComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rc3R1ZGVudHMvc3R1ZGVudHMtc3BvbnNvci1sZXR0ZXJzL3N0dWRlbnRzLXNwb25zb3ItbGV0dGVycy5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ja2FwaWxsYS9EZXYvSm92ZW5lc0EtY2xpZW50LkNMSS9zcmMvYXBwLytzdHVkZW50cy9zdHVkZW50cy1zcG9uc29yLWxldHRlcnMvc3R1ZGVudHMtc3BvbnNvci1sZXR0ZXJzLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
