/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './students.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './shared/students-navbar/students-navbar.component.ngfactory';
import * as i3 from '../../../../src/app/+students/shared/students-navbar/students-navbar.component';
import * as i4 from '../../../../src/app/app_shared/services/session.service';
import * as i5 from '@angular/router';
import * as i6 from '../../../../src/app/+students/students.component';
import * as i7 from '../../../../src/app/app_shared/services/auth.service';
const styles_StudentsComponent:any[] = [i0.styles];
export const RenderType_StudentsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_StudentsComponent,data:{}});
export function View_StudentsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'students-navbar',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_StudentsNavbarComponent_0,
      i2.RenderType_StudentsNavbarComponent)),i1.ɵdid(49152,(null as any),0,i3.StudentsNavbarComponent,
      [i4.SessionService],(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(212992,(null as any),0,i5.RouterOutlet,[i5.ChildrenOutletContexts,i1.ViewContainerRef,
          i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,4,0);
  },(null as any));
}
export function View_StudentsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'ja-students',
      ([] as any[]),(null as any),(null as any),(null as any),View_StudentsComponent_0,
      RenderType_StudentsComponent)),i1.ɵdid(49152,(null as any),0,i6.StudentsComponent,
      [i7.Auth],(null as any),(null as any))],(null as any),(null as any));
}
export const StudentsComponentNgFactory:i1.ComponentFactory<i6.StudentsComponent> = i1.ɵccf('ja-students',
    i6.StudentsComponent,View_StudentsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rc3R1ZGVudHMvc3R1ZGVudHMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rc3R1ZGVudHMvc3R1ZGVudHMuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9ja2FwaWxsYS9EZXYvSm92ZW5lc0EtY2xpZW50LkNMSS9zcmMvYXBwLytzdHVkZW50cy9zdHVkZW50cy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rc3R1ZGVudHMvc3R1ZGVudHMuY29tcG9uZW50LnRzLlN0dWRlbnRzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHN0dWRlbnRzLW5hdmJhcj48L3N0dWRlbnRzLW5hdmJhcj5cblxuPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuIiwiPGphLXN0dWRlbnRzPjwvamEtc3R1ZGVudHM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTsyQ0FBQSxVQUFBO01BQUEsaURBQW1DO01BQUEsV0FFbkM7TUFBQTthQUFBO3NDQUFBO1VBQUEsZUFBK0I7SUFBL0I7Ozs7b0JDRkE7TUFBQTtrQ0FBQSxVQUFBO01BQUE7OzsifQ==
