/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/+students/students.module';
import * as i2 from './students.component.ngfactory';
import * as i3 from './students-home/students-home.component.ngfactory';
import * as i4 from './students-profile/students-profile.component.ngfactory';
import * as i5 from './students-sponsor-letters/students-sponsor-letters.component.ngfactory';
import * as i6 from './sponsor-letters-add/sponsor-letters-add.component.ngfactory';
import * as i7 from '@angular/common';
import * as i8 from '@angular/forms';
import * as i9 from '@angular/router';
import * as i10 from '../../../../src/app/app_shared/app_shared.module';
import * as i11 from '../../../../src/app/+students/students.component';
import * as i12 from '../../../../src/app/app.routing-guards';
import * as i13 from '../../../../src/app/+students/students-home/students-home.component';
import * as i14 from '../../../../src/app/+students/students-profile/students-profile.component';
import * as i15 from '../../../../src/app/+students/students-sponsor-letters/students-sponsor-letters.component';
import * as i16 from '../../../../src/app/+students/sponsor-letters-add/sponsor-letters-add.component';
export const StudentsModuleNgFactory:i0.NgModuleFactory<i1.StudentsModule> = i0.ɵcmf(i1.StudentsModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.StudentsComponentNgFactory,i3.StudentsHomeComponentNgFactory,i4.StudentsProfileComponentNgFactory,
              i5.StudentsSponsorLettersComponentNgFactory,i6.SponsorLettersAddComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i7.NgLocalization,
          i7.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i8.FormBuilder,i8.FormBuilder,
          ([] as any[])),i0.ɵmpd(4608,i8.ɵi,i8.ɵi,([] as any[])),i0.ɵmpd(512,i7.CommonModule,
          i7.CommonModule,([] as any[])),i0.ɵmpd(512,i9.RouterModule,i9.RouterModule,
          [[2,i9.ɵa],[2,i9.Router]]),i0.ɵmpd(512,i8.ɵba,i8.ɵba,([] as any[])),i0.ɵmpd(512,
          i8.ReactiveFormsModule,i8.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,
          i8.FormsModule,i8.FormsModule,([] as any[])),i0.ɵmpd(512,i10.AppSharedModule,
          i10.AppSharedModule,([] as any[])),i0.ɵmpd(512,i1.StudentsModule,i1.StudentsModule,
          ([] as any[])),i0.ɵmpd(1024,i9.ROUTES,() => {
        return [[{path:'students',component:i11.StudentsComponent,canActivate:[i12.CanActivateViaStudentAuthGuard],
            children:[{path:'',pathMatch:'full',component:i13.StudentsHomeComponent},
                {path:'home',component:i13.StudentsHomeComponent},{path:'profile/:id',
                    component:i14.StudentsProfileComponent},{path:'sponsor-letters/:id',
                    component:i15.StudentsSponsorLettersComponent},{path:'sponsor-letters-add/:studentId/:sponsorId',
                    component:i16.SponsorLettersAddComponent}]}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rc3R1ZGVudHMvc3R1ZGVudHMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC8rc3R1ZGVudHMvc3R1ZGVudHMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
