/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/app_shared/components/display-errors.component';
import * as i1 from '@angular/forms';
import * as i2 from './display-errors.component.ngfactory';
export function DisplayErrorsComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.DisplayErrorsComponent,diDeps:[{isAttribute:false,
      isHost:true,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.FormGroupDirective}}}],
      lifecycleHooks:([] as any[])},isComponent:true,selector:'display-errors',exportAs:(null as any),
      inputs:{errors:'errors',control:'control'},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i2.View_DisplayErrorsComponent_0,
      rendererType:i2.RenderType_DisplayErrorsComponent,componentFactory:i2.DisplayErrorsComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC9hcHBfc2hhcmVkL2NvbXBvbmVudHMvZGlzcGxheS1lcnJvcnMuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvY2thcGlsbGEvRGV2L0pvdmVuZXNBLWNsaWVudC5DTEkvc3JjL2FwcC9hcHBfc2hhcmVkL2NvbXBvbmVudHMvZGlzcGxheS1lcnJvcnMuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
